[package]
name = "particle-cells"
version = "0.1.0"
authors = ["Jordan Matelsky <j6k4m8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.16"